version: "3.8"

services:
  event-service:
    build:
      context: ./
      dockerfile: event-service/Dockerfile
    container_name: challenge-3-event-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  mongodb:
    image: mongo:latest
    container_name: challenge-3-mongo-db-production
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local