spring:
  application:
    name: ticket-manager
  data:
    mongodb:
      uri: mongodb://admin:admin@mongodb:27017/db_ticket?authSource=admin

event-manager:
  url: http://localhost:8080

server:
  port: 8081

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true