spring:
  application:
    name: event-manager
  data:
    mongodb:
      uri: mongodb://admin:admin@mongodb:27017/db_event?authSource=admin

ticket-manager:
  url: http://localhost:8081

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true